version: "3.8"


services:
# config server config
  mongo_1_config:
    image: mongo
    container_name: mg_db_1
    command: mongod --configsvr --replSet cfgrs --port 27017 --dbpath /data/db
    ports:
      - "3333:27017"
    
    volumes:
      - mongo_1_config:/data/db


  mongo_2_config:
    image: mongo
    container_name: mg_db_2
    restart: unless-stopped
    command: mongod --configsvr --replSet cfgrs --port 27017 --dbpath /data/db
    ports:
      - "3334:27017"

    volumes:
      - mongo_2_config:/data/db


  mongo_3_config:
    image: mongo
    container_name: mg_db_3
    restart: unless-stopped
    command: mongod --configsvr --replSet cfgrs --port 27017 --dbpath /data/db
    ports:
      - "3335:27017"

    volumes:
      - mongo_3_config:/data/db
  

  shard1s1:
    container_name: shard1s1
    image: mongo
    command: mongod --shardsvr --replSet shard1rs --port 27017 --dbpath /data/db
    ports:
      - 20001:27017
    volumes:
      - shard1s1:/data/db

  shard1s2:
    container_name: shard1s2
    image: mongo
    command: mongod --shardsvr --replSet shard1rs --port 27017 --dbpath /data/db
    ports:
      - 20002:27017
    volumes:
      - shard1s2:/data/db

  shard1s3:
    container_name: shard1s3
    image: mongo
    command: mongod --shardsvr --replSet shard1rs --port 27017 --dbpath /data/db
    ports:
      - 20003:27017
    volumes:
      - shard1s3:/data/db


  mongos:
    container_name: mongos
    image: mongo
    command: mongos --configdb cfgrs/mg_db_1:27017,mg_db_2:27017,mg_db_3:27017 --bind_ip 0.0.0.0 --port 27017
    ports:
      - 30000:27017

  init-config:
    image: mongo
    depends_on:
      - mongo_1_config
      - mongo_2_config
      - mongo_3_config
      - shard1s1
      - shard1s2
      - shard1s3
      - mongos
    volumes:
      - ./init.sh:/cluster-init.sh
    entrypoint: ["bash", "/init.sh"]


volumes:
  mongo_1_config: {}
  mongo_2_config: {}
  mongo_3_config: {}
  shard1s1: {}
  shard1s2: {}
  shard1s3: {}

