  services:
    mongo_1_config:
      image: mongo:7
      container_name: mongo_1_config
      command: mongod --configsvr --replSet cfgrs --wiredTigerCacheSizeGB 0.25 --port 27017 --dbpath /data/db
      ports:
        - "3333:27017"
      volumes:
        - mongo_1_config:/data/db
      
      networks:
        - mongo-cluster

    mongo_2_config:
      image: mongo:7
      container_name: mongo_2_config
      restart: unless-stopped
      command: mongod --configsvr --replSet cfgrs --wiredTigerCacheSizeGB 0.25 --port 27017 --dbpath /data/db
      ports:
        - "3334:27017"
      volumes:
        - mongo_2_config:/data/db
      
      networks:
        - mongo-cluster

    mongo_3_config:
      image:  mongo:7
      container_name: mongo_3_config
      restart: unless-stopped
      command: mongod --configsvr --replSet cfgrs --wiredTigerCacheSizeGB 0.25 --port 27017 --dbpath /data/db
      ports:
        - "3335:27017"
      volumes:
        - mongo_3_config:/data/db
      
      networks:
        - mongo-cluster

    # shard 1
    shard1s1:
      image:  mongo:7
      container_name: shard1s1
      restart: unless-stopped
      command: mongod --shardsvr --replSet shard1rs --wiredTigerCacheSizeGB 0.25 --port 27017 --dbpath /data/db
      ports:
        - 20001:27017
      volumes:
        - shard1s1:/data/db
      
      networks:
        - mongo-cluster

    shard1s2:
      image:  mongo:7
      container_name: shard1s2
      restart: unless-stopped
      command: mongod --shardsvr --replSet shard1rs --wiredTigerCacheSizeGB 0.25 --port 27017 --dbpath /data/db
      ports:
        - 20002:27017
      volumes:
        - shard1s2:/data/db
      
      networks:
        - mongo-cluster

    shard1s3:
      image:  mongo:7
      container_name: shard1s3
      restart: unless-stopped
      command: mongod --shardsvr --replSet shard1rs --wiredTigerCacheSizeGB 0.25 --port 27017 --dbpath /data/db
      ports:
        - 20003:27017
      volumes:
        - shard1s3:/data/db
      
      networks:
        - mongo-cluster

    # shard 2
    shard2s1:
      image:  mongo:7
      container_name: shard2s1
      restart: unless-stopped
      command: mongod --shardsvr --replSet shard2rs --wiredTigerCacheSizeGB 0.25 --port 27017 --dbpath /data/db
      ports:
        - 20004:27017
      volumes:
        - shard2s1:/data/db
      
      networks:
        - mongo-cluster

    shard2s2:
      image:  mongo:7
      container_name: shard2s2
      restart: unless-stopped
      command: mongod --shardsvr --replSet shard2rs --wiredTigerCacheSizeGB 0.25 --port 27017 --dbpath /data/db
      ports:
        - 20005:27017
      volumes:
        - shard2s2:/data/db
      
      networks:
        - mongo-cluster

    shard2s3:
      image:  mongo:7
      container_name: shard2s3
      restart: unless-stopped
      command: mongod --shardsvr --replSet shard2rs --wiredTigerCacheSizeGB 0.25 --port 27017 --dbpath /data/db
      ports:
        - 20006:27017
      volumes:
        - shard2s3:/data/db
      
      networks:
        - mongo-cluster

    mongos:
      image:  mongo:7
      container_name: mongos
      restart: unless-stopped
      ports:
        - 30000:27017

      volumes:
        - ./mongos-entrypoint.sh:/mongos-entrypoint.sh

      entrypoint: ["/bin/sh", "/mongos-entrypoint.sh"]

      networks:
        - mongo-cluster
      

    init-config:
      image: mongo
      depends_on:
        - mongo_1_config
        - mongo_2_config
        - mongo_3_config
        - shard1s1
        - shard1s2
        - shard1s3
        - shard2s1
        - shard2s2
        - shard2s3
        - mongos
      volumes:
        - ./cluster-init.sh:/init.sh
      entrypoint: ["/bin/sh", "/init.sh"]

      networks:
        - mongo-cluster

  volumes:
    mongo_1_config:
    mongo_2_config:
    mongo_3_config:
    shard1s1:
    shard1s2:
    shard1s3:
    shard2s1:
    shard2s2:
    shard2s3:

  networks:
    mongo-cluster: